### ISSUE TITLE
BotBase.cpp passa parâmetro errado para thrusters laterais

### ISSUE THREAD

**Issue by andrehp** [topfreegames/top-asteroids-challenge#3]
No método BotBase::Update() as linhas 28 e 29 estão com os parâmetros como a variável thrust, quando eles deveriam ser sideThrustFront e sideThrustBack, respectivamente.

**Comment by pzucco** [comment]
Corrigido no commit 828445c76af0ba61cbe7b7bc8f7e000b0dc5fb1d
