### ISSUE TITLE
Pedras não estão sendo adicionadas ao mapa de pedras em C++

### ISSUE THREAD

**Issue by andrehp** [topfreegames/top-asteroids-challenge#4]
No bot_interface.cpp as pedras não estão sendo adicionadas corretamente no mapa de pedras.

O motivo desse bug é a linha 243, onde está shipIds deveria ser rockIds

**Comment by pzucco** [comment]
Olá,
Corrigido no commit cbf7b330a820f05e05b776bd3eb3634831b81a3d
